name: Create Release

on:
  workflow_dispatch:

jobs:
  release-changelog:
    name: Changelog & Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: üõ°Ô∏è Obtain GitOpsLover Installation Access Token
        id: app_auth
        run: |
          TOKEN="$(npx obtain-github-app-installation-access-token ci ${{ secrets.GITOPSLOVER_APP_TOKEN }})"
          
          echo "::add-mask::$TOKEN"
          echo "::set-output name=token::$TOKEN"

      - name: üì• Checkout the code
        uses: actions/checkout@v4

      - name: Update Changelog
        id: changelog
        uses: TriPSs/conventional-changelog-action@v5.2.0
        with:
          github-token: ${{ steps.app_auth.outputs.token }}
          version-file: './package.json,./package-lock.json'
          git-user-name: 'gitopslover[bot]'
          git-user-email: '160535767+gitopslover[bot]@users.noreply.github.com'

      